### ISSUE TITLE
Keyword detection bug

### ISSUE THREAD

**Issue by stpp2** [wahyunurarizky/seo-content-analyzer#15]
@wahyunurarizky - great job on this little tool!

Seems like the keyword detection is a little off if there are special characters around keywords.
For example, when you set your keyword to `this is a keyphrase` - the following cases won't get detected:
```
Quotes around "this is a keyphrase" would cause issues. 
A comma or dot: this is a keyphrase. // <-- not detected
```

Would be awesome to get better detection in these cases.
(also - I think the latest NPM release isn't up to date with this repo?)

Thanks!

**Comment by wahyunurarizky** [comment]
I see, thanks, I'll try to fix it later.

**Comment by stpp2** [comment]
@wahyunurarizky - thanks! It'd be really great to improve the keyword detection

**Comment by stpp2** [comment]
Thanks for the fix! Are you planning to also bump the npm package with the new version?
